//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int Emp_NO { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_Location { get; set; }
        public string Emp_Phone { get; set; }
        public string Dept_No { get; set; }
        public string Dept_Name { get; set; }
        public string Salary { get; set; }
        public Nullable<int> Job_ID { get; set; }
    }
}
